// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"

	"github.com/spf13/cobra"
)

type hyattSplitStayOption struct {
	CheckinDate  string          `json:"checkinDate"`
	CheckoutDate string          `json:"checkoutDate,omitempty"`
	Nights       int             `json:"nights"`
	MaxSwitches  int             `json:"maxSwitches"`
	Options      []hyattAwardRow `json:"options"`
}

// pp:data-source local
func newNovelAwardsSplitStayCmd(flags *rootFlags) *cobra.Command {
	var flagHotels string
	var flagStart string
	var flagEnd string
	var flagNights int
	var flagMaxSwitches int
	var flagRoomCategories string
	var dbPath string

	cmd := &cobra.Command{
		Use:         "split-stay",
		Short:       "Build viable multi-hotel Hyatt itineraries when no one property has the full stay.",
		Example:     "  hyatt-pp-cli awards split-stay --hotels CHIRH,CHIJD --start 2026-08-01 --end 2026-08-15 --nights 5 --max-switches 1 --agent",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			if flagNights < 1 {
				return usageErr(fmt.Errorf("--nights must be >= 1"))
			}
			rows, err := localHyattRows(cmd, flags, dbPath)
			if err != nil {
				return err
			}
			rows = filterAwardRows(rows, flagHotels, "", flagStart, flagEnd, flagNights, flagRoomCategories)
			byDate := map[string][]hyattAwardRow{}
			for _, row := range rows {
				if row.Available {
					byDate[row.Date] = append(byDate[row.Date], row)
				}
			}
			dates := make([]string, 0, len(byDate))
			for date := range byDate {
				dates = append(dates, date)
			}
			sort.Strings(dates)
			out := make([]hyattSplitStayOption, 0, len(dates))
			for _, date := range dates {
				options := byDate[date]
				sort.Slice(options, func(i, j int) bool {
					return options[i].PointsValue < options[j].PointsValue
				})
				out = append(out, hyattSplitStayOption{
					CheckinDate: date,
					Nights:      flagNights,
					MaxSwitches: flagMaxSwitches,
					Options:     options,
				})
			}
			return printJSONFiltered(cmd.OutOrStdout(), out, flags)
		},
	}
	cmd.Flags().StringVar(&flagHotels, "hotels", "", "Comma-separated Hyatt spirit codes")
	cmd.Flags().StringVar(&flagStart, "start", "", "Start date YYYY-MM-DD")
	cmd.Flags().StringVar(&flagEnd, "end", "", "End date YYYY-MM-DD")
	cmd.Flags().IntVar(&flagNights, "nights", 1, "Length of stay to match")
	cmd.Flags().IntVar(&flagMaxSwitches, "max-switches", 1, "Maximum hotel switches to allow")
	cmd.Flags().StringVar(&flagRoomCategories, "room-categories", "STANDARD_ROOM", "Room categories to include")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/hyatt-pp-cli/data.db)")
	return cmd
}
