// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

// pp:data-source local
func newNovelAwardsCertificateFitCmd(flags *rootFlags) *cobra.Command {
	var flagCert string
	var flagExpires string
	var flagStart string
	var flagEnd string
	var flagHotels string
	var flagNights int
	var flagRoomCategories string
	var dbPath string

	cmd := &cobra.Command{
		Use:         "certificate-fit",
		Short:       "Find available Hyatt award nights that fit a Cat 1-4 or Cat 1-7 certificate before it expires.",
		Example:     "  hyatt-pp-cli awards certificate-fit --cert cat1-4 --expires 2026-12-31 --start 2026-09-01 --end 2026-12-31 --nights 1 --agent",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			maxCat := categoryMax(flagCert)
			if maxCat == 0 {
				return usageErr(fmt.Errorf("--cert must be cat1-4 or cat1-7"))
			}
			rows, err := localHyattRows(cmd, flags, dbPath)
			if err != nil {
				return err
			}
			rows = filterAwardRows(rows, flagHotels, "", flagStart, flagEnd, flagNights, flagRoomCategories)
			out := make([]hyattAwardRow, 0, len(rows))
			for _, row := range rows {
				if !row.Available || row.Category == 0 || row.Category > maxCat {
					continue
				}
				if strings.TrimSpace(flagExpires) != "" && !dateBeforeOrEqual(row.Date, flagExpires) {
					continue
				}
				out = append(out, row)
			}
			return printJSONFiltered(cmd.OutOrStdout(), out, flags)
		},
	}
	cmd.Flags().StringVar(&flagCert, "cert", "", "Certificate type: cat1-4 or cat1-7")
	cmd.Flags().StringVar(&flagExpires, "expires", "", "Certificate expiration date YYYY-MM-DD")
	cmd.Flags().StringVar(&flagStart, "start", "", "Start date YYYY-MM-DD")
	cmd.Flags().StringVar(&flagEnd, "end", "", "End date YYYY-MM-DD")
	cmd.Flags().StringVar(&flagHotels, "hotels", "", "Optional comma-separated Hyatt spirit codes")
	cmd.Flags().IntVar(&flagNights, "nights", 1, "Length of stay to match")
	cmd.Flags().StringVar(&flagRoomCategories, "room-categories", "STANDARD_ROOM", "Room categories to include")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/hyatt-pp-cli/data.db)")
	return cmd
}
