// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

// pp:data-source local
func newNovelAwardsRoomLadderCmd(flags *rootFlags) *cobra.Command {
	var flagHotel string
	var flagStart string
	var flagEnd string
	var flagNights int
	var dbPath string

	cmd := &cobra.Command{
		Use:         "room-ladder",
		Short:       "Compare standard, club, and suite award availability side by side for one Hyatt stay window.",
		Example:     "  hyatt-pp-cli awards room-ladder --hotel CHIRH --start 2026-10-01 --end 2026-10-07 --nights 1 --agent",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			if flagHotel == "" {
				return usageErr(fmt.Errorf("--hotel is required"))
			}
			rows, err := localHyattRows(cmd, flags, dbPath)
			if err != nil {
				return err
			}
			rows = filterAwardRows(rows, flagHotel, "", flagStart, flagEnd, flagNights, "")
			return printJSONFiltered(cmd.OutOrStdout(), rows, flags)
		},
	}
	cmd.Flags().StringVar(&flagHotel, "hotel", "", "Hyatt spirit code")
	cmd.Flags().StringVar(&flagStart, "start", "", "Start date YYYY-MM-DD")
	cmd.Flags().StringVar(&flagEnd, "end", "", "End date YYYY-MM-DD")
	cmd.Flags().IntVar(&flagNights, "nights", 1, "Length of stay to match")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/hyatt-pp-cli/data.db)")
	return cmd
}
