// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNovelAwardsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "awards",
		Short:       "awards subcommands: certificate-fit, coverage, density, offpeak, room-ladder, split-stay",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}
	cmd.AddCommand(newNovelAwardsCertificateFitCmd(flags))
	cmd.AddCommand(newNovelAwardsCoverageCmd(flags))
	cmd.AddCommand(newNovelAwardsDensityCmd(flags))
	cmd.AddCommand(newNovelAwardsOffpeakCmd(flags))
	cmd.AddCommand(newNovelAwardsRoomLadderCmd(flags))
	cmd.AddCommand(newNovelAwardsSplitStayCmd(flags))
	return cmd
}
