// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCalendarsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagSpiritCode string
	var flagStartDate string
	var flagEndDate string
	var flagRooms int
	var flagAdults int
	var flagKids string
	var flagRate string
	var flagRoomCategory string
	var flagVrcEnabled bool

	cmd := &cobra.Command{
		Use:         "calendars",
		Short:       "Fetch a Hyatt Points Calendar page for a hotel spirit code",
		Long:        "Fetch a Hyatt Points Calendar page for a hotel spirit code",
		Example:     "  hyatt-pp-cli calendars --spirit-code example-value",
		Annotations: map[string]string{"pp:endpoint": "calendars.get", "pp:method": "GET", "pp:path": "/explore-hotels/rate-calendar", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("spirit-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "spirit-code")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/explore-hotels/rate-calendar"
			htmlRequestParams := map[string]string{}
			if flagSpiritCode != "" {
				htmlRequestParams["spiritCode"] = formatCLIParamValue(flagSpiritCode)
			}
			if flagStartDate != "" {
				htmlRequestParams["startDate"] = formatCLIParamValue(flagStartDate)
			}
			if flagEndDate != "" {
				htmlRequestParams["endDate"] = formatCLIParamValue(flagEndDate)
			}
			if flagRooms != 0 {
				htmlRequestParams["rooms"] = formatCLIParamValue(flagRooms)
			}
			if flagAdults != 0 {
				htmlRequestParams["adults"] = formatCLIParamValue(flagAdults)
			}
			if flagKids != "" {
				htmlRequestParams["kids"] = formatCLIParamValue(flagKids)
			}
			if flagRate != "" {
				htmlRequestParams["rate"] = formatCLIParamValue(flagRate)
			}
			if flagRoomCategory != "" {
				htmlRequestParams["roomCategory"] = formatCLIParamValue(flagRoomCategory)
			}
			if flagVrcEnabled != false {
				htmlRequestParams["vrcEnabled"] = formatCLIParamValue(flagVrcEnabled)
			}
			params := map[string]string{}
			if flagSpiritCode != "" {
				params["spiritCode"] = formatCLIParamValue(flagSpiritCode)
			}
			if flagStartDate != "" {
				params["startDate"] = formatCLIParamValue(flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = formatCLIParamValue(flagEndDate)
			}
			if flagRooms != 0 {
				params["rooms"] = formatCLIParamValue(flagRooms)
			}
			if flagAdults != 0 {
				params["adults"] = formatCLIParamValue(flagAdults)
			}
			if flagKids != "" {
				params["kids"] = formatCLIParamValue(flagKids)
			}
			if flagRate != "" {
				params["rate"] = formatCLIParamValue(flagRate)
			}
			if flagRoomCategory != "" {
				params["roomCategory"] = formatCLIParamValue(flagRoomCategory)
			}
			if flagVrcEnabled != false {
				params["vrcEnabled"] = formatCLIParamValue(flagVrcEnabled)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "calendars", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if !flags.dryRun {
				if parsed, ok := enhanceHyattCalendarData(data, htmlRequestParams); ok {
					data = parsed
				} else {
					data, err = extractHTMLResponse(data, htmlExtractionOptions{
						Mode:           "page",
						BaseURL:        htmlExtractionRequestURL(c.BaseURL, path, htmlRequestParams),
						ContentType:    c.LastContentType(),
						LinkPrefixes:   []string{},
						Limit:          0,
						ScriptSelector: "script#__NEXT_DATA__",
						JSONPath:       "",
					})
					if err != nil {
						return err
					}
				}
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSpiritCode, "spirit-code", "", "Hyatt hotel spirit code, such as kulal for Alila Bangsar Kuala Lumpur")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Check-in date in YYYY-MM-DD format")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Checkout date in YYYY-MM-DD format.")
	cmd.Flags().IntVar(&flagRooms, "rooms", 1, "Number of rooms")
	cmd.Flags().IntVar(&flagAdults, "adults", 1, "Number of adult guests")
	cmd.Flags().StringVar(&flagKids, "kids", "0", "Number of child guests")
	cmd.Flags().StringVar(&flagRate, "rate", "Standard", "Hyatt rate selector, usually Standard for points calendars")
	cmd.Flags().StringVar(&flagRoomCategory, "room-category", "STANDARD_ROOM", "Hyatt points-calendar room category")
	cmd.Flags().BoolVar(&flagVrcEnabled, "vrc-enabled", true, "Enable Hyatt variable redemption calendar")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
