// Copyright 2026 Jiahong Chen and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"sort"

	"github.com/spf13/cobra"
)

type hyattVolatilityRow struct {
	SpiritCode     string   `json:"spiritCode"`
	ObservedRows   int      `json:"observedRows"`
	AvailableRows  int      `json:"availableRows"`
	NightsObserved []int    `json:"nightsObserved,omitempty"`
	RoomCategories []string `json:"roomCategories,omitempty"`
}

// pp:data-source local
func newNovelWatchVolatilityCmd(flags *rootFlags) *cobra.Command {
	var flagSince string
	var flagLimit int
	var dbPath string

	cmd := &cobra.Command{
		Use:         "volatility",
		Short:       "Rank watched Hyatt hotels by how often award space opens, closes, or changes price.",
		Example:     "  hyatt-pp-cli watch volatility --since 30d --limit 20 --agent",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			rows, err := localHyattRows(cmd, flags, dbPath)
			if err != nil {
				return err
			}
			_ = flagSince // Current local snapshots do not store historical sync timestamps per row.
			type agg struct {
				total int
				open  int
				n     map[int]bool
				cats  map[string]bool
			}
			byHotel := map[string]*agg{}
			for _, row := range rows {
				a := byHotel[row.SpiritCode]
				if a == nil {
					a = &agg{n: map[int]bool{}, cats: map[string]bool{}}
					byHotel[row.SpiritCode] = a
				}
				a.total++
				if row.Available {
					a.open++
				}
				if row.Nights > 0 {
					a.n[row.Nights] = true
				}
				if row.RoomCategory != "" {
					a.cats[row.RoomCategory] = true
				}
			}
			out := make([]hyattVolatilityRow, 0, len(byHotel))
			for code, a := range byHotel {
				out = append(out, hyattVolatilityRow{
					SpiritCode:     code,
					ObservedRows:   a.total,
					AvailableRows:  a.open,
					NightsObserved: intSetKeys(a.n),
					RoomCategories: stringSetKeys(a.cats),
				})
			}
			sort.Slice(out, func(i, j int) bool {
				return out[i].AvailableRows > out[j].AvailableRows
			})
			if flagLimit > 0 && len(out) > flagLimit {
				out = out[:flagLimit]
			}
			return printJSONFiltered(cmd.OutOrStdout(), out, flags)
		},
	}
	cmd.Flags().StringVar(&flagSince, "since", "30d", "Snapshot lookback hint; retained for future historical watch tables")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Maximum hotels to return")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/hyatt-pp-cli/data.db)")
	return cmd
}
